#Note: If you are on a sever it needs to have this mod installed, or otherwise allow you to send messages with 'ยง' in them.
#Enable/disable typing ยง in text fields
Enabled = true
#Enable/disable using extended syntax, such as ยง[blue][u]hello
"Enable extended syntax" = true
#Enable/disable using hex codes. If disabled, all custom hex codes will be hidden and ignored.
"Enable hex codes" = true
#Enable/disable markdown formatting, such as *italic* or **bold**.
"Enable markdown" = true

